"""1

Revision ID: 6f2d99a1d717
Revises: 1714032c8650
Create Date: 2020-12-09 00:05:44.774007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2d99a1d717'
down_revision = '1714032c8650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
